services:
  - type: web
    name: alx-travel-app
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn alx_travel_app.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"

  - type: worker
    name: celery-worker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A alx_travel_app worker --loglevel=info
    envVars:
      - key: SECRET_KEY
        generateValue: true